### ISSUE TITLE
在安装界面部分键盘无法使用和海康威视NVME无法识别

### ISSUE THREAD

**Issue by hackerwxsk** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#14]
先贴配置
CPU:9700K
主板:EFI-ASRock-Z390-Phantom-Gaming-ITX
BIOS:1.4
内存:金士顿骇客神条16G DDR4 2400*2
显卡：暂无
电源：海韵SF650
鼠标：罗技G102
SSD：NVME海康威视C2000 256G,其他SATA接口的SSD
键盘：魔力鸭ducky zero 2108机械键盘

使用该EFI安装10.14.4，10.14.5，10.14.6都有如下问题
1.在Clover时可以正常识别使用（魔力鸭ducky zero 210）键盘，一旦进入安装界面，键盘无法使用，连键盘灯都不亮，换了其他杂牌薄膜键盘却可以使用，就这个（魔力鸭ducky zero 210）键盘用不了。

2.进入安装界面后，磁盘工具无法抹掉NVME的SSD(海康威视C2000 256G)，安装系统也无法选择该NVME的SSD，对SATA的SSD可以正常抹掉和安装

**Comment by icyleaf** [comment]
试着把 BIOS 升级或降级看看

**Comment by hackerwxsk** [comment]
最开始的BIOS版本描述错了，我现在的BIOS版本是4.0
之前已试过如下BIOS版本
1.3
1.5
1.6
这两个问题依旧

**Comment by hackerwxsk** [comment]
官网初版BIOS版本就是1.2，为了解决这两个问题，我从初始版本1.2到现在的4.0都刷遍了，这两个问题依旧，应该不是BIOS问题

**Comment by hackerwxsk** [comment]
![捕获](https://user-images.githubusercontent.com/51780334/64306931-fa38a000-cfc6-11e9-87a3-9d4bf55036bd.PNG)

**Comment by icyleaf** [comment]
我之前用的是Apple原装键盘，现在用的是垃圾货自己改的用着都没问题，那只可能是魔力鸭键盘固件的问题吧，你看看这个 https://www.reddit.com/r/MechanicalKeyboards/comments/54q4g8/0300help_ducky_zero_not_working_in_macos_sierra/

**Comment by hackerwxsk** [comment]
键盘通过上面的固件升级解决了，NVME的问题，我将MACOS安装在SATA盘里后，通过MACOS再格式化NVME盘后安装程序能重新识别NVME了
