### ISSUE TITLE
换网卡

### ISSUE THREAD

**Issue by XziSun** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#15]
请问换网卡需要将天线也更换吗？还是只要更换那块卡就是了呢？望解答，感激不尽。

**Comment by icyleaf** [comment]
更换原有的无线模块即可，具体看我首页 README 博客文章

--
/**
* About me
*
* @author icyleaf
* @url http://icyleaf.com
* @version always beta
*/
2019年10月3日 +0800 14:35 XziSun <notifications@github.com>，写道：

**Comment by XziSun** [comment]
噢，真的太感谢了。谢谢！！

**Comment by XziSun** [comment]
请问如果我的cpu是9400，那么需不需要更改EFI呢？

**Comment by icyleaf** [comment]
这个就不太清楚了，你可以多准备几个 EFI 试试

**Comment by icyleaf** [comment]
问题先关了，有问题在重开
