### ISSUE TITLE
升级 macOS Catalina 10.15

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#16]
先升级 Clover 及必要的 kexts。

需要注意的点  Clover r4xxx 到 r5xxx 目录结构发生变化升级需注意，可参考[本教程](https://www.tonymacx86.com/threads/how-to-update-clover-v2-4k-r4xxx-to-v2-5k-r5xxx-v2-4k-r4972-to-v2-5-r5018-example.281428/)

- [x] 升级 Clover 至 r5xxx 以上（已升级到 r5078） 1cb4ff27191ae9142544bc643ae5ccbfe0492032
- [x] 升级必要的 Kexts，比如 Lilu、AppleALC、WhateverGreen、BrcmFirmwareRepo 等，同时同步到 `/Library/Extensions` 2c68d4f0a62dd7818d8bd4d6c75e7602f74c5c9f
- [x] 下载 macOS Catalina.app
- [x] 升级 macOS Catalina.app

升级 Catalina 的注意事项：

- [黑客小兵: macOS Catalina 10.15安装中常见的问题及解决方法](https://blog.daliansky.net/Common-problems-and-solutions-in-macOS-Catalina-10.15-installation.html)
- [Bugprogrammer: macOS Catalina 10.15目前情况(持续更新)](https://www.bugprogrammer.me/2019/06/04/hackintosh-10.15.html)
- [醉渔小站: macOS Catania 10.15 beta3 上车体验及开启 sidecar 方法](https://zuiyu1818.cn/posts/Hac_Catania_beta3_sidecar.html)

 相关 issue #9

**Comment by icyleaf** [comment]
昨天折腾了一宿安装的时候也没注意以为安装重启选错了启动项造成引导时直接黑屏，今天尝试了进恢复模式重装系统（昨天不知为什么无法在线重新安装，今天可以了但耗时特别长就取消了此念头），从 USB 引导启动识别、重新从 USB 安装也失败。

最后想了下会不会是内存的问题（Clover 删除了 AptioMemoryFix.efi 也没用其他的内存修正 efi），最后想着要不然试试恢复板载显卡就成功进入了系统。。。

正常工作：

- [ ] 有线网络
- [ ] 蓝牙

目前遇到的问题：

- [ ] 独立显卡不可用
- [ ] 无线可识别但无法连接

<img width="885" alt="截屏2019-10-1910 43 02" src="https://user-images.githubusercontent.com/17814/67136791-15e9c400-f25e-11e9-8c1e-84ad1fec181a.png">

**Comment by icyleaf** [comment]
自己二了吧唧的，忘记了同步 `/Library/Extensions` 的 kexts，使用 KextBeast 同步 `AppleALC`、`Lilu` 和 `WhateverGreen` 后重启声卡（layout = 7）和独立显卡恢复正常。

**Comment by icyleaf** [comment]
观察一段时间如果没问题关闭此问题

**Comment by icyleaf** [comment]
还是参考[替RX 580顯卡開啟eGPU加速和HEVC硬體解碼，支援FCPX](https://mrmad.com.tw/fix-rx580-egpu-hevc-fcpx-high-sierra) 的设置恢复之前的启动参数用于开启 eGPU 的硬件加速。

**Comment by icyleaf** [comment]
无线网卡有时莫名会掉速，不确定是家里 WIFI 覆盖问题（确实是有死角）还是驱动问题。

**Comment by ansonliao** [comment]
@icyleaf 
看iterm上的显示，请问你是香港的么?

**Comment by icyleaf** [comment]
@ansonliao 那个是自己设置的，忽略即可

**Comment by icyleaf** [comment]
换了辅助路由器后发现 WIFI 正常，此问题可以结贴。
