### ISSUE TITLE
TB3 HotPlug Have a try.  https://github.com/al3xtjames/ThunderboltPkg

### ISSUE THREAD

**Issue by fangf2018** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#18]
TB3 HotPlug Have a try.  https://github.com/al3xtjames/ThunderboltPkg

**Comment by icyleaf** [comment]
我看你之前有个停更的 EFI 有用 [TB3 的 DTST](https://github.com/fangf2018/ASRock-Z390-Phantom-ITX-Clover-Hackintosh/blob/master/EFI/CLOVER/ACPI/patched/SSDT-TB3.aml) 好使吗？

**Comment by fangf2018** [comment]
需要开机前插入设备，不是最佳方案。都是都白果移植的。

**Comment by icyleaf** [comment]
我目前没有任何雷电3的设备所以说还好，不是着急的事情

**Comment by icyleaf** [comment]
放在 #16 处理，暂时先关闭
