### ISSUE TITLE
休眠后wifi无法打开， 或者关闭wifi后无法继续打开

### ISSUE THREAD

**Issue by Henry-Zheng** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#2]
我用的是z390 extreme 4, BCM943602CS转PCIE卡
我出现问题时休眠后wifi无法打开， 或者关闭wifi后无法继续打开，不知道你有木有同样的问题，谢谢

**Comment by icyleaf** [comment]
对于你的这个板子不清楚。最好你去社区搜索看看，你看看 config.plist 的内容设置是否一致。
