### ISSUE TITLE
ASRock-Z390-Phantom-Gaming-ITX 10.15无法正常关机重启

### ISSUE THREAD

**Issue by feidr525** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#20]
我的配置跟你的差不多装了10.15一直无法重启无法正常关机希望能帮助我一下 ### **怎么联系到你留个方式谢谢``_

1. 

- [ ]  #@

_**

**Comment by icyleaf** [comment]
直接使用我的 EFI 板载显卡和 rx5x0 系列显卡是没问题的，使用前先记得备份自己的 EFI。

**Comment by icyleaf** [comment]
有问题再开先关闭了
