### ISSUE TITLE
打完uhd630核显缓冲桢补丁后没有4K

### ISSUE THREAD

**Issue by ansonliao** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#21]
@icyleaf ，
谢谢分享教程和EFI，我的显示器就是根据妳的贴子买的LG 27UL600的，

我的主板也是Asrock Z390 phantom gaming ITX-AC，CPU是i5-9600K，没有独显，用的是核显UHD630 (够用就行)。

现在在10.14.6下面，看起来显示是正常的， 如下面那样
![image](https://user-images.githubusercontent.com/6060224/67946381-3df10400-fc1c-11e9-8f57-8ca878d28689.png)
![image](https://user-images.githubusercontent.com/6060224/67946572-97f1c980-fc1c-11e9-912f-ab3bb6c1066d.png)
![image](https://user-images.githubusercontent.com/6060224/67946601-a4762200-fc1c-11e9-91cf-0da13765d328.png)

后来看到了 [黑果小兵的用Hackintool给UHD630打缓冲桢补丁](https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html#%E6%A0%B8%E5%BF%83%E5%8A%9F%E8%83%BD%E7%BB%99%E7%BC%93%E5%86%B2%E5%B8%A7%E6%89%93%E8%A1%A5%E4%B8%81) 的说法，自己就按着操作，但是打完补丁后就不正常了，界面很模糊，显示设置里面缩放只剩下几个分辨率可选，没有了上面图片中的那些`large text`，`more space`这些图例了，分辨率最大也只有2000多x1000多的，看起来就是最多就是1920x1080分辨率。

我把妳的EFI下载下来，用clover或plistedit pro打开，发现妳也没有像黑果小兵那样给UHD630打缓冲桢补丁的痕迹。

另外，曾经尝试过升级到10.15.0，但升级完后，开机登入到显示桌面期间会有短暂的黑屏，唤醒时也会，黑屏时间不一定，有时几秒，有时几分钟，然后网上都说要打UHD 630缓存桢补丁，但打完补丁后就是分辨率没有4K。

请问需要打这个补丁么?

谢谢。

**Comment by ansonliao** [comment]
@icyleaf 
请问妳是用什么镜像装的黑苹果?

我是用黑果小兵做的10.14.6的镜像。

前几天我又用黑果小兵的10.14.6的镜像重装了一次，装完后，其实是进不了系统的，应该是smbios的机型不对，好在第一次安装的时候是的EFI是可用的，所以把第一次安装的EFI覆盖就可以进系统了。

EFI覆盖后，进了系统也是有4K的。
昨天晚上又试着把10.14.6升级到catalina，有4K的，但还是会短暂黑屏的问题。

自己觉得，是某些驱动问题，毕竟黑果小兵的镜像是通用型的，可能有很多自己机型用不着的驱动。
已经将whatevergreen，lilu，applealc这些升级到最新的了，只是问题短暂黑屏问题还在。

**Comment by icyleaf** [comment]
我是用的苹果官方的，使用的 kexts 都是 EFI 里面。

--
/**
* About me
*
* @author icyleaf
* @url http://icyleaf.com
* @version always beta
*/
2019年11月1日 +0800 09:59 ansonliao <notifications@github.com>，写道：

**Comment by ansonliao** [comment]
明白，如果试要用妳的EFI，因为我没有独显，和CPU不一样，需要改动些什么?
@icyleaf ，谢谢!!

**Comment by ansonliaomelco** [comment]
自己从app store上下载了catalina，做了U盘，用了妳的EFI后，发现启动界面图标没了，请问是什么问题? @icyleaf 
谢谢!

![image](https://user-images.githubusercontent.com/55119017/68051875-69aae180-fd23-11e9-8bb3-03d5bee22ec8.png)

**Comment by icyleaf** [comment]
这是 Clover 的主题，你可能没有

**Comment by icyleaf** [comment]
@ansonliao 你可以看下 4b62090358f812c0734eff805d8c14a55e031906 之前的 commit 的 EFI 配置，我记得我没做什么太多的改动

**Comment by icyleaf** [comment]
@ansonliao 如何还没解决建议可以参考下这个帖子 https://www.tonymacx86.com/threads/success-asrock-z390-phantom-gaming-itx-tb3-igpu-mojave-sff-build.277418/

**Comment by ansonliao** [comment]
@icyleaf 
搞定了!!!!!

在这个贴子里(https://www.tonymacx86.com/threads/success-asrock-z390-phantom-gaming-itx-tb3-igpu-mojave-sff-build.277418/)，贴主给我发了一个`config.plist`也没有搞定，不过后来tonymaxc86不知道为什么把我的帐号给banned掉了，所以把我的全部贴子和回复都给删掉了，现在也无法告知贴主最新的进度。

解决方法是: `framebuffer-stolenmem`要注释掉或删掉，建议删掉，如下图所示

![image](https://user-images.githubusercontent.com/6060224/68987266-3314b100-0863-11ea-9f3a-c5f82f1b448f.png)

另外，根据tonymacx86上的贴子(https://www.tonymacx86.com/threads/success-asrock-z390-phantom-gaming-itx-tb3-igpu-mojave-sff-build.277418/)，我在BIOS里，把`Advanced\Chipset Configuration\Primary Graphics Adapter`设成`Onboard`，把`Advanced\Chipset Configuration\Shared Memory`设成了`256M`，

![image](https://user-images.githubusercontent.com/6060224/68987282-6b1bf400-0863-11ea-8e9d-c88e407a64db.png)

**Comment by ansonliao** [comment]
接下来就看看升级到catalina后，会不会有短暂的黑屏了，之前试过会有短暂的黑屏情况出现(之前没有把FB给打上，就算用上最新的weg和lilu，现在打上了，不知道会不会解决catalina短暂黑屏问题)

**Comment by icyleaf** [comment]
你之前的 BIOS `Primary Graphics Adapter`  设置不是 `OnBoard` 吗，这个是板载显卡。

**Comment by ansonliao** [comment]
刚开始，`BIOS Primary Graphic Adapter` 设置的是PCI-E的，不过就算设成 `OnBoard`后，打FB补丁不把 `framebuffer-stolenmem` 去掉也是不行的

**Comment by MihuSeen** [comment]
@ansonliaomelco 哥们 我也碰到了 没有选项的问题 请问你是怎么解决的

**Comment by ansonliaomelco** [comment]
@MihuSeen , 看这里
https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/issues/21#issuecomment-554599452

**Comment by MihuSeen** [comment]
@ansonliaomelco 已经解决了 谢谢啦
