### ISSUE TITLE
有时候会突然画面卡住动弹不得

### ISSUE THREAD

**Issue by terryops** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#22]
给你反馈一下：
我跟你一样的主板，CPU 是 9700F，显卡是 5700XT，内存是科赋的 DDR4 3200。
我之前用AptioMemoryFix，有时候会突然画面卡住动弹不得。
现在换成你用的OsxAptioFix3Drv.efi，现在还在测试。
为什么你没用AptioMemoryFix呢？

**Comment by icyleaf** [comment]
AptioMemoryFix 在 10.15 上有问题

**Comment by terryops** [comment]
换了OsxAptioFix3Drv.efi也还是会卡住。
有点烦恼……不知道哪里出了问题。
我用的是 VirtualSMC，会不会是这个缘故？

**Comment by icyleaf** [comment]
这个只能不断的尝试，祝你好运！
