### ISSUE TITLE
您好，请问EFI/CLOVER/目录中没有drivers64UEFI吗？

### ISSUE THREAD

**Issue by q944093** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#24]
我现在系统是10.14，如果想用您的EFI升级10.15，是不是要保留我之前的drivers64UEFI文件夹，然后把跟您EFI相同的文件夹替换掉就可以了？还是直接把旧的EFI全删掉，把您的EFI复制进去呢？

**Comment by icyleaf** [comment]
请看 #23
