### ISSUE TITLE
请问下使用了哪个BIOS版本？

### ISSUE THREAD

**Issue by huyinjie** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#25]
在[博文](https://icyleaf.com/2019/03/asrock-z390-gaming-itx-install-hackintosh-tutorial/)写的0.5.0版本在[官网](https://www.asrock.com/mb/Intel/Z390%20Phantom%20Gaming-ITXac/index.cn.asp#BIOS)上没有，最低也就1.20版本

**Comment by icyleaf** [comment]
博文打错了，应该是 `1.5`，抱歉。

**Comment by huyinjie** [comment]
发现自己的主板到手就是4.2，这个版本不能降级了。在U盘安装时卡在了IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0，未能看到苹果图标。请问有什么方法吗~

**Comment by huyinjie** [comment]
我的配置是Z390 Phantom Gaming itx/ac+9600K没有显卡，请问下是否是显卡所影响的问题

**Comment by icyleaf** [comment]
https://www.tonymacx86.com/threads/success-asrock-z390-phantom-gaming-itx-tb3-igpu-mojave-sff-build.277418/ 这里写的建议保留在 1.6 版本，4.0 以上版本可能会屏闪理论上不会出现你说的问题。我觉得可能还是其他原因，这个我没遇到过。

--
/**
* About me
*
* @author icyleaf
* @url http://icyleaf.com
* @version always beta
*/
2019年12月10日 +0800 17:48 Yinjie Hu <notifications@github.com>，写道：

**Comment by icyleaf** [comment]
顺便建议使用官方镜像，黑锅小兵的貌似会出奇奇怪怪的问题

--
/**
* About me
*
* @author icyleaf
* @url http://icyleaf.com
* @version always beta
*/
2019年12月10日 +0800 17:48 icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX <reply@reply.github.com>，写道：
>
> IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0

**Comment by huyinjie** [comment]
好的感谢 我使用的是官方镜像。
一开始Clover写入后，U盘引导遇到了没有安装系统选项的问题。后来使用UniBeast-9.2.0重新烧录，按照博文的方法替换kexts后可以进入到安装系统的步骤~不过应该不是这个原因

**Comment by huyinjie** [comment]
会尝试使用编程器降级BIOS看看会不会继续出现这些问题

**Comment by icyleaf** [comment]
你的问题这里有 https://blog.daliansky.net/Common-problems-and-solutions-in-macOS-Mojave-10.14-installation.html

**Comment by huyinjie** [comment]
嗯我之前就是这样配置的，没有勾选Inject Intel。我试试第二种方法，实在不行尝试下降级BIOS了

**Comment by icyleaf** [comment]
祝你好运

**Comment by huyinjie** [comment]
更新：
（BIOS4.2版本，UEFI启动开启）不要删除EFI下的driver64目录。
重新烧录了一遍镜像，Clover界面一直没安装选项，添加driver64目录后就有了。
现在使用UniBeast-9.2.0烧录+替换大佬的EFI/CLOVER/kexts/Ohter和config.list文件后成功进入安装界面。
并将driver64目录中的AptioMemoryFix-64.efi替换为[OsxAptioFix2Drv-free2000.efi](https://hackintosher.com/wp-content/uploads/2017/07/OsxAptioFix2Drv-free2000.efi_.zip)解决安装过程中一个BSD kernel panic
成功安装，感谢大佬

**Comment by icyleaf** [comment]
你的 Clover 版本是 2.4k 还是 2.5k？

**Comment by huyinjie** [comment]
v2.4k r4910

icyleaf <notifications@github.com>于2019年12月11日 周三下午1:50写道：

**Comment by icyleaf** [comment]
v2.4k 和 v2.5k 的目录结构是不一样的，你应该是用的最新的所以出错了 ，具体可以看 #16

**Comment by huyinjie** [comment]
想起来了 用了Unibeast烧录系统后直接使用了你的EFI文件 应该是最新版Clover安装了10.14.6系统

icyleaf <notifications@github.com>于2019年12月11日 周三下午6:38写道：
