### ISSUE TITLE
哥们儿 ，谢谢你的配置了。

### ISSUE THREAD

**Issue by onlymcdz** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#28]
我一个在深圳做广告创意的 ，也研究黑苹果配置。 最近新增电脑需求 ； 看了你一天的配置 下单中……

**Comment by onlymcdz** [comment]
以后跟你混了， 就看看配置在这里写 。管不管用；

**Comment by onlymcdz** [comment]
还有想问几个问题： 1.你的配置中 SSD 是用M2 插槽？ 在整机中的位置、兼容性、散热性如何？2. 显卡位置可以上两片显卡交火吗？ 黑果子里可以实现双卡交火？

**Comment by onlymcdz** [comment]
还有两个问题想问下你已在使用机型 ；1. SSD 是用M2插槽的，里面的空间对影片散热性能OK吗？黑果子对M2 兼容性如何？ 2. 按照你的配置，机箱还有空间上双显卡交火吗？ 黑果子对这套双显卡交火向上扩容性好吗？

**Comment by icyleaf** [comment]
这个板子就只有一个 PCI-E 你咋装俩显卡 = =!

M2 和 SATA 都可以插，哪个效率高就用哪个。

**Comment by icyleaf** [comment]
没有回应先关闭了
