### ISSUE TITLE
十分感谢

### ISSUE THREAD

**Issue by mumoing** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#29]
组装的时候 主板无线网卡 都是按这个配置买的，现在已经能成功跑起来了。不过我的显卡是rx5700xt 安装的也是10.15.2版本的，用集显跑的时候没问题 用核显跑的进不去登录界面。 不知这个需要改哪些配置呢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by icyleaf** [comment]
rx5700xt 我记得是 10.15.1 开始原生支持的，没有测试过。可能需要你改下机型，而且现有的独显的配置可能不适用你的显卡。我的 EFI 只适用于 rx 5x0 的显卡，我没法帮到你，你在去看看社区的情况吧。

**Comment by icyleaf** [comment]
从 https://github.com/khronokernel/Anti-Hackintosh-Buyers-Guide/blob/master/GPU.md 这里看来尽量不要使用你使用的显卡

**Comment by mumoing** [comment]
> 从 https://github.com/khronokernel/Anti-Hackintosh-Buyers-Guide/blob/master/GPU.md 这里看来尽量不要使用你使用的显卡

好的，谢谢你的建议。
