### ISSUE TITLE
成功驱动 RX 5700 xt

### ISSUE THREAD

**Issue by KisCG** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#30]
尝试了一下，成功驱动了RX 5700 xt，给后面的人分享一下。

@mumoing, @icyleaf

**主要问题出在 Graphics 里面，要把 Inject Intel 和 Inject ATI 都取消勾选。**

同时建议 Boot 里面关于 Shiki 的也可以全部删了，Shiki已经deprecated了，相关功能已经整合到了WEG里面。

-disablegfxfirmware 也可以删了

> For Coffee Lake, setting ig-platform-id or -disablegfxfirmware boot flag is no longer needed. Instead, we need to add "change GFX0 to IGPU" (find 47465830 replace 49475055) and "change PEGP to GFX0" (find 50454750 replace 47465830) patches to DSDT. Make sure the former is patched before the latter or something very wrong is going to happen.

然后加上 agdpmod=pikera

注意升级到最新的 lilu，WEG 和 Clover

最后感谢@icyleaf 分享的文件和教程

_Originally posted by @mumoing in https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/issues/29#issuecomment-568345870_

**Comment by mumoing** [comment]
正在寻找解决方案中... 谢谢你的方案。 我来尝试一下

**Comment by mumoing** [comment]
已经能够驱动成功了，再次感谢。 
![image](https://user-images.githubusercontent.com/35980988/71418415-5f62ef00-26a5-11ea-919d-b80122607f58.jpg)

**Comment by icyleaf** [comment]
已添加到 README，感谢 @KisCG 的反馈
