### ISSUE TITLE
2x16G 内存升级到 2x32G 后无法引导10.15.2系统

### ISSUE THREAD

**Issue by AaronZYHK** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#31]
谢谢你的经验+文件分享。

我使用过的是你post 的 EFI  本来一切顺利 安装完成后自己改了三码 改成了 iMac 2019 的机型。

但是我把之前用的两条16G内存升级为两条32G内存后，发现无法引导，clover 进入MacOS 后卡在最前面 只是提到了可能是OsxAptioFix3Drv 的问题。

不知道这个怎么处理？ 是需要替换在这个OsxAptioFix3Drv 为其他的？ 还是说需要在config.list 里面加上内存的信息？求救，谢谢。我用的黑峰岭，所以换一次内存就得拆一次散热，已经来来回回拆了四次，涂了四次硅脂了 T T

谢谢大大了

**Comment by AaronZYHK** [comment]
我自己解决了 
需要手动把2x32的内存映射成四根16G的 需要在楼主饿config.list里面加内存映射。加上就好了

**Comment by icyleaf** [comment]
资料参考：[Mapping RAM and DIMM Slots on a Hackintosh with Clover SMBIOS)](https://hackintosher.com/forums/thread/mapping-ram-and-dimm-slots-on-a-hackintosh-with-clover-smbios.365/)
