### ISSUE TITLE
开启SideCar（随航）功能

### ISSUE THREAD

**Issue by KisCG** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#32]
# 开启SideCar（随航）功能

## 问题

@icyleaf 默认给的 config 是开启不了 SideCar 的。（连接上了也只会黑屏没有任何内容。）

问题出在 **SMBIOS** 的选择上，默认的 iMacPro1,1 是一款没有核显只有独显的型号。也就是没有 **iGPU** 只有 **dGPU**。

**而要正确的启用 SideCar 必须要 iGPU 的解码加速**。白果的 iMacPro1,1 能够正常启用的原因是因为有 T2 芯片，替代了核显的作用，做 on-the-fly encoding。而我们的黑果没有，所以一定要用有核显的 GPU。

> PS. 好像没有核显也不是完全不能用，但是据说效果会非常模糊，也会很卡。本人没有测试过，感兴趣的可以自行参考[这篇文章](https://blog.fangf.cc/2019/10/14/noneigpusidecar/)。

### 1. SMBIOS

所以为了 SideCar 能正常运行，我们第一步要做的就是把 SMBIOS 改成 **iMac19,1** 。

生成新的 Serial Number 跟新的 SmUUID。

![SMBIOS](https://tva1.sinaimg.cn/large/006tNbRwgy1gabzoq3yw3j32bc0u0kjm.jpg)

其他一些跟原config文件不一样的地方。

### 2. ACPI

![Acpi](https://tva1.sinaimg.cn/large/006tNbRwgy1gabzl1yp7hj31o50u07wh.jpg)

DSDT 里面那两行被我在 #30 加上又注掉了，原因是没有必要。详情请看最后面的*参考链接*。

### 3. Graphics

![Graphics](https://tva1.sinaimg.cn/large/006tNbRwgy1gabzl12yhwj31nv0u0qsn.jpg)

**没错，就是什么都不要填。** WEG 会自己轻轻松松找到准确的配置。WEG 自从整合了什么IntelGraphicsFixup, NvidiaGraphicsFixup, Shiki and CoreDisplayFixup 等等 kexts 之后，已经变成了一个 all-in-one solution，十分方便。

> 关于 Intel Coffee Lake 核显的 FAQ：
> [Coffee Lake](https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/coffee-lake)
> [Intel Framebuffer patching using WhateverGreen](https://www.insanelymac.com/forum/topic/334899-intel-framebuffer-patching-using-whatevergreen/)

### 4. Boot

![Boot](https://tva1.sinaimg.cn/large/006tNbRwgy1gabzwwrs8cj31oe0u0ty8.jpg)

这里因为测试过没有问题，Debug 用的 Flag 和没用的 Flag 都被我删掉了。

> 关于各种 Flag 的解释和教程可以参考：
> [WhateverGreen Github](https://github.com/acidanthera/WhateverGreen)
> [Hackintosh Vanilla Coffee Lake](https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/coffee-lake#devices)
> [An iDiot's Guide To Lilu and its Plug-ins](https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/)

### 4. BIOS

最后要在主板 BIOS 设定里面 **开启** ` IGPU Multi-Monitor `。

> Turn on iGPU ever, is not only for sidecar, avoid freezes, bug in preview, encoder/decoder, etc. 

### 关于DRM

我自己测试 Netflix，Amazon Prime Video，Apple Music Video 等等都是没有问题的。有问题的朋友可以反馈一下。

**Comment by icyleaf** [comment]
这个成功案例很干货，置顶一下以表感谢

**Comment by lushibin** [comment]
无独显，按教程配置下来，还是不成功，随航 ipad，总是提示 设备超时

**Comment by KisCG** [comment]
> 无独显，按教程配置下来，还是不成功，随航 ipad，总是提示 设备超时

1. 检查黑苹果跟iPad设备要求
2. 黑苹果跟iPad都登出Apple ID并重启设备后再登入试试
3. Wi-Fi不行用数据线试试
4. Sidebar、Touch Bar 不勾选试试

**Comment by pittance72** [comment]
12代 13代intel cpu即使有核顯也不能用sidecar 
可能是因為蘋果沒這兩代的核顯驅動
