### ISSUE TITLE
后置面板麦克风接口无声音输入

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#35]
麦克风选用的是飞利浦的： https://item.jd.com/126744.html
是这个设备不兼容嘛？

**Comment by icyleaf** [comment]
抱歉，没有这个需求也没研究过。

**Comment by Android-AwesomeRoy** [comment]
参照 [这篇文章](https://hackintosher.com/guides/get-hackintosh-audio-working/)修改plist文件后可用，但是需要选择 「内置麦克风」 才能识别。
![image](https://user-images.githubusercontent.com/19187129/75323273-801b1100-58af-11ea-8a2c-c68b324395bf.png)

**Comment by icyleaf** [comment]
有问题再开
