### ISSUE TITLE
自动睡眠失效和莫名自动唤醒的问题

### ISSUE THREAD

**Issue by TrainTsang** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#39]
重装了10.15.3，使用10.15的clover，出现了以下问题
1、息屏后无法自动睡眠（这个问题其他地方说是10.15的常见问题）
2、手动睡眠后，经常在半夜5点、早上9点，莫名其妙自动唤醒

显卡 RX590 蓝宝石
CPU 9900KF

节能设置
息屏：15分钟
防止自动睡眠：未勾选
硬盘睡眠：勾选
以太唤醒：勾选、未勾选都试过
小憩：未勾选

**Comment by icyleaf** [comment]
有用户反馈开启了提醒事项或者备忘录之类的系统 App 可能会造成被唤醒，个人从升级到 10.15 一直没有遇到过自动唤醒了。

**Comment by icyleaf** [comment]
有用户反馈开启了提醒事项或者备忘录之类的系统 App 可能会造成被唤醒，个人从升级到 10.15 一直没有遇到过自动唤醒了。

**Comment by TrainTsang** [comment]
> 有用户反馈开启了提醒事项或者备忘录之类的系统 App 可能会造成被唤醒，个人从升级到 10.15 一直没有遇到过自动唤醒了。

还真是，不仅黑苹果被唤醒了，白苹果都唤醒了。只是因为黑苹果自动睡眠有问题，所以一直开着。白苹果过一会儿就自己休息了。
