### ISSUE TITLE
这款主板不支持NVRAM写入么?

### ISSUE THREAD

**Issue by imEgo** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#40]
如题看到两款华擎的主板都加了EmuVariableUefi.efi，是都不支持NVRAM写入么，之前用的微星和技嘉的都支持最近打算换这个板子，特来咨询望解答

**Comment by icyleaf** [comment]
呃，最初直接借用的 tonymacx86 的 kexts 一直沿用过来的，没做测试。

**Comment by icyleaf** [comment]
稍微研究了一下从[这里](https://www.tonymacx86.com/threads/mojave-on-asrock-z390-phantom-gaming-itx-ac.265245/page-7#post-1958977)的讨论来看是 AptioMemoryFix-64.efi 依赖 EmuVariable。

**Comment by imEgo** [comment]
> 稍微研究了一下从[这里](https://www.tonymacx86.com/threads/mojave-on-asrock-z390-phantom-gaming-itx-ac.265245/page-7#post-1958977)的讨论来看是 AptioMemoryFix-64.efi 依赖 EmuVariable。

并不是的，这两个没有强关联，如果主板支持macOS下写入nvram是不需要EmuVariable，我自己的msi b150就是AptioMemoryFix但是没有EmuVariable，不然还要使用脚本来保存nvram需要修改系统

**Comment by icyleaf** [comment]
原帖里面讨论的已经解释的很清楚了我只是摘出了一个引子，那你可以按照你的理解来，买不买这个板子是你自己的决定 :)

**Comment by icyleaf** [comment]
算了再给你补充点吧，给其他搜到的朋友看答案：

> 苹果并没有推出搭载 z390 芯片组的产品，因此 macOS 现有版本无法也不能支持 nvram，只能模拟！如果你是去年年初问我，我还会告诉你苹果连 9 代 CPU 也不“支持” 因为他们没有推出相关产品。

**Comment by imEgo** [comment]
> 算了再给你补充点吧，给其他搜到的朋友看答案：
> 
> > 苹果并没有推出搭载 z390 芯片组的产品，因此 macOS 现有版本无法也不能支持 nvram，只能模拟！如果你是去年年初问我，我还会告诉你苹果连 9 代 CPU 也不“支持” 因为他们没有推出相关产品。

感谢解答，原来300系还不支持，那我也帮你补充下，如何判断自己的主板是否原生支持NVRAM，给其他搜到的朋友看答案

去掉直接EmuVariableUefi.efi引导进入macOS系统，命令行里执行sudo nvram NVRAMTest=OK，重启，再次进入macOS系统后，命令行里执行nvram -p | grep NVRAMTest，如果有值输出就说明支持NVRAM，不输出说明需要EmuVariableUefi.efi，反之需要添加这个efi并且需要CLOVER的脚本来保存NVRAM到nvram.plist实现完整的功能，比如音量背光等等都会通过NVRAM来保存，当然缺点就是需要修改系统；
如果你跟我一样没有主机板没办法测试，只能找一些别人的配置看看有没有EmuVariableUefi.efi，当然要找技术好的，不然可能会对自己误导

另外补充
因为之前看到有别人的微星和技嘉的Z390I的配置里没有EmuVariableUefi.efi，所以特意查了下找到一篇如何300系主板上实现原生NVRAM，因为我的CPU和主板还在路上，无法验证是否有效，但是下面H370也有成功的，应该是OK的：
https://www.reddit.com/r/hackintosh/comments/erd2th/nvram_for_all_300_series_users_rejoice

**Comment by imEgo** [comment]
华擎Z390m-ITX/ac，在10.15.4上经测试使用CLOVER + AptioMemoryFix.efi，删除EmuVariableUefi.efi，通过添加SSDT-PMC.aml的方案可以原生实现的NVRAM

**Comment by icyleaf** [comment]
> 华擎Z390m-ITX/ac，在10.15.4上经测试使用CLOVER + AptioMemoryFix.efi，删除EmuVariableUefi.efi，通过添加SSDT-PMC.aml的方案可以原生实现的NVRAM

最近在看 opencore 挖坑下，这个方案的来源：https://dortania.github.io/hackintosh/updates/2020/01/20/nvram.html
