### ISSUE TITLE
[有问题暂时回滚] 升级 macOS 10.15.4

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#41]
待做事项：

- [x] 备份系统（TimeMachine 或 CCC） **重要，重要，重要**
- [x] 升级 Clover r5107
- [x] 升级 Lilu 1.3.8 以上
- [x] 升级 AppleALC  1.4.2 以上
- [x] 升级 WhateverGreen  1.3.7 以上

升级后状态：

第一次重启升级结束时提醒 `The bless tool was unable to set the current boot disk` 只能重启，重启我没选择升级的引导后进入系统发现已经显示升级至 10.15.4 重启还会有升级引导进入提示找不到引导盘，发现的问题的睡眠后[唤醒 LG 4K 显示器会激活 HDR 模式](https://www.tonymacx86.com/threads/macos-10-15-4-update.292646/page-2#post-2089681)，目前不太确定是驱动问题还是什么，因为有 TimeMachine 暂时回滚 10.15.3。

自我反省：

不要跟风 reddit 的成功案例，最好等 tonymacx86 有更好的时间验证后再升级！

Ref: 
https://www.tonymacx86.com/threads/macos-10-15-4-update.292646/

**Comment by Android-AwesomeRoy** [comment]
老哥不考虑研究一下 OpenCore 吗?

**Comment by icyleaf** [comment]
github 有人用的是opencore 你可以去找找

**Comment by icyleaf** [comment]
<img width="586" alt="截屏2020-03-28 11 34 19" src="https://user-images.githubusercontent.com/17814/77813992-1b3e1b00-70e8-11ea-8a3e-a4262fb32127.png">

升级时提示我因为某些原因（没记住）无法安装之后重启没有选引导启动，采用默认 macOS 启动后卡了一会再进去发现升级成功，我在观察观察

**Comment by muscleant** [comment]
首先谢谢分享EFI文件，同主板。我是之前安装的10.15.3，前几天升级上来的，更新后有个报错是关于设置启动盘的，因为我是双系统，报错也正常，所以没管，可以顺利进系统，后来发现睡眠唤醒后容易重启，重构下kext似乎好了，目前没有再发生。

**Comment by ettwz** [comment]
感谢分享。
我的Z-390A升级到10.15.4以后重启或者开机时bios会进入安全模式，不知道有没有遇到过的

**Comment by icyleaf** [comment]
> 感谢分享。
> 我的Z-390A升级到10.15.4以后重启或者开机时bios会进入安全模式，不知道有没有遇到过的

呃，这里应该都是 asrock 的板子吧。

**Comment by ettwz** [comment]
> > 感谢分享。
> > 我的Z-390A升级到10.15.4以后重启或者开机时bios会进入安全模式，不知道有没有遇到过的
> 
> 呃，这里应该都是 asrock 的板子吧。

哦哦，好的。
不过您那个教程我基本上参考了80%都是ok的。谢谢大佬

**Comment by tuutoo** [comment]
我的就是LG的 同样会自动HDR,现在可以这样解决,参考这个帖子.
注入EDID,强制RGB显示就可以了.
https://www.tonymacx86.com/threads/10-15-4-update-how-to-disable-hdr-support.293991/page-2

我的主板和你的一样的 但是升了10.15.4后, 前置音频不起作用. 10.14.6时是好的... 不知道有人有同样问题不.

**Comment by tuutoo** [comment]
> 我的就是LG的 同样会自动HDR,现在可以这样解决,参考这个帖子.
> 注入EDID,强制RGB显示就可以了.
> https://www.tonymacx86.com/threads/10-15-4-update-how-to-disable-hdr-support.293991/page-2
> 
> 我的主板和你的一样的 但是升了10.15.4后, 前置音频不起作用. 10.14.6时是好的... 不知道有人有同样问题不.

声音的问题也找到解决方法了.  Lilu在升了10.15后,在启动参数要加 -lilubetaall

**Comment by dypan** [comment]
> 我的就是LG的 同样会自动HDR,现在可以这样解决,参考这个帖子.
> 注入EDID,强制RGB显示就可以了.
> https://www.tonymacx86.com/threads/10-15-4-update-how-to-disable-hdr-support.293991/page-2
> 
> 我的主板和你的一样的 但是升了10.15.4后, 前置音频不起作用. 10.14.6时是好的... 不知道有人有同样问题不.

提示~The bless tool was unable to set the current boot disk~ 算是升级成功还是没成功？

**Comment by qbeenslee** [comment]
同样采用本EFI, 升级到10.15.4时报了`The bless tool was unable to set the current boot disk`, 然后也是能顺利进入系统, 并且系统显示已经升级到10.15.4.
升级到10.15.4后, 已经日常使用了2周, 发现存在的问题: 
* [ ] app store无app更新提示
* [ ] 系统无法更新升级
* [ ] 系统睡眠后容易被唤醒

---
不知道 老哥你那边有什么新的收获不?

**Comment by icyleaf** [comment]
@qbeenslee 回滚了，最近一直在忙就没有升级。

**Comment by dypan** [comment]
`The bless tool was unable to set the current boot disk` 我找到了解决方案，使用Clover Configurator将"Default Boot Volume"修改成macOS volume名（我的就叫mac），然后重启，重启后升级10.15.4无此错误提示。
详情：https://www.tonymacx86.com/threads/after-10-15-4-update-cannot-set-current-boot-disk.294002/page-2#post-2091440

**Comment by icyleaf** [comment]
由于 macOS 10.15.4 有 ssh 的 bug，暂不升级：https://mp.weixin.qq.com/s/knqQh4JBFT8JvpEDd4La3w

**Comment by feidr525** [comment]
> 待做事项：
> 
> * [x]  备份系统（TimeMachine 或 CCC） **重要，重要，重要**
> * [x]  升级 Clover r5107
> * [x]  升级 Lilu 1.3.8 以上
> * [x]  升级 AppleALC  1.4.2 以上
> * [x]  升级 WhateverGreen  1.3.7 以上
> 
> 升级后状态：
> 
> 第一次重启升级结束时提醒 `The bless tool was unable to set the current boot disk` 只能重启，重启我没选择升级的引导后进入系统发现已经显示升级至 10.15.4 重启还会有升级引导进入提示找不到引导盘，发现的问题的睡眠后[唤醒 LG 4K 显示器会激活 HDR 模式](https://www.tonymacx86.com/threads/macos-10-15-4-update.292646/page-2#post-2089681)，目前不太确定是驱动问题还是什么，因为有 TimeMachine 暂时回滚 10.15.3。
> 
> 自我反省：
> 
> 不要跟风 reddit 的成功案例，最好等 tonymacx86 有更好的时间验证后再升级！
> 
> Ref:
> https://www.tonymacx86.com/threads/macos-10-15-4-update.292646/

我得也是lg hdr 显示器 升级10.15.4以后 自动开启了hdr 但是我把显示器dp版本从1.4 调整到1.2以后 没有什么问题了 睡眠以后唤醒照常工作 希望对你有帮助

**Comment by icyleaf** [comment]
直接跳过本版本，直接升级到了 10.15.5 :)

**Comment by icyleaf** [comment]
@feidr525 试了你的方法不可以的，正确的方法是进系统设置-显示器，勾掉“高动态范围”的选项就好了，我查了[原因](https://www.youtube.com/watch?v=CFyNBYP5lJk)是 macOS 10.15.4 开始会自动识别显示器设置并默认开启 HDR
