### ISSUE TITLE
插入u盘和移动硬盘在disk utility中被识别为内置usb硬盘

### ISSUE THREAD

**Issue by linseedoil** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#42]
**问题描述**

插入u盘和移动硬盘在disk utility中被识别为内置usb硬盘，但二者还略有不同，u盘还可以默认被挂载在桌面，移动硬盘就不可以，finder设置中桌面不显示内置硬盘。

尝试了几种tonymacx86上方法都没有解决:
1. 在clover configurator中，acpi下，change ech1 to ec01 and change ech2 to ec02
2. 勾选fix sata
3. 勾选fix usb会导致无法开机

虽然不影响使用，打开finder后也能找到硬盘使用，但还是希望能解决，谢谢。

**硬件信息**

- 主板：same
- CPU：same
- 显卡：5700xt

**截图**
<img width="925" alt="issue_demo" src="https://user-images.githubusercontent.com/65097557/81488423-2ebdd380-929b-11ea-9a49-73671bdb9811.png">

如果需要可以附加上

**软件信息**

- Clover 版本：
- 相关 Kexts 和版本：

** Clover 配置**

有必要可以上传 Clover 的配置文件

**Comment by icyleaf** [comment]
最近太忙了，周末看看。或者我记得可以用 hacktools 调整

**Comment by linseedoil** [comment]
> 最近太忙了，周末看看。或者我记得可以用 hacktools 调整

好的。谢谢。我也再研究一下，我试试hackintool看

**Comment by icyleaf** [comment]
<img width="573" alt="截屏2020-05-1323 22 25" src="https://user-images.githubusercontent.com/17814/81832283-e8a19200-9570-11ea-8c05-5e583ac9d8e7.png">

目前所有 USB 设置都是内置的

**Comment by linseedoil** [comment]
> <img alt="截屏2020-05-1323 22 25" width="573" src="https://user-images.githubusercontent.com/17814/81832283-e8a19200-9570-11ea-8c05-5e583ac9d8e7.png">
> 
> 目前所有 USB 设置都是内置的

有方法能改成外置usb3吗？我刚试了一下直接选usb3然后点注入重启不行。我不太了解hackintool

**Comment by linseedoil** [comment]
> > <img alt="截屏2020-05-1323 22 25" width="573" src="https://user-images.githubusercontent.com/17814/81832283-e8a19200-9570-11ea-8c05-5e583ac9d8e7.png">
> > 目前所有 USB 设置都是内置的
> 
> 有方法能改成外置usb3吗？我刚试了一下直接选usb3然后点注入重启不行。我不太了解hackintool

看到了hackintool里面的说明，我明天先根据说明试一下，之前不好意思没仔细研究就伸手，打扰了

**Comment by linseedoil** [comment]
> 目前所有 USB 设置都是内置的

多谢你指出的解决方向。

按照hackintool里面的教程一步一步实现，可以完美解决这个问题，附上最后生成的USBPorts.kext，我猜相同主板应该可以通用？不过我不太确定。附一张最后解决后的截图

<img width="2014" alt="external_recognized_internal" src="https://user-images.githubusercontent.com/65097557/81945542-d25b0b00-9630-11ea-8522-bdd5334eafbd.png">

[USBPorts.kext.zip](https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/files/4628955/USBPorts.kext.zip)

**Comment by icyleaf** [comment]
嗯，正常这个主板都是可以通用的，加个教程的标签。目前对于我没啥太大影响，会不会内部和 USB3 的速度会有差别？

**Comment by linseedoil** [comment]
> 嗯，正常这个主板都是可以通用的，加个教程的标签。目前对于我没啥太大影响，会不会内部和 USB3 的速度会有差别？

速度应该没有差别，应该只是一个识别标签的问题。区别是如果是USB3移动硬盘就可以被识别为外置，插上就可以直接挂载到桌面，不用进finder打开了
