### ISSUE TITLE
可以用来进行iOS开发吗？

### ISSUE THREAD

**Issue by Snailovet** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#44]
用来iOS开发与白苹果有区别吗？
编译速度贵快吗？

**Comment by icyleaf** [comment]
和白苹果没有任何区别，编译速度取决于你的 CPU、内存

**Comment by Snailovet** [comment]
了解

icyleaf <notifications@github.com>于2020年5月20日 周三下午6:54写道：
