### ISSUE TITLE
求助 Boot failed: will sleep for 10 seconds before exiting... 问题

### ISSUE THREAD

**Issue by huyinjie** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#45]
系统是10.15.4，使用本仓库的EFI无法进入系统，提示 Boot failed: will sleep for 10 seconds before exiting

![photo_2020-05-26_13-04-26](https://user-images.githubusercontent.com/8533957/82862122-74dc8d80-9f51-11ea-8abd-4f3e844c6d9b.jpg)

**硬件信息**
- 主板：ASRock-Z390-Phantom-Gaming-ITX
- CPU：i5-9600K
- 内存：8Gx2
- 显卡：无

**软件信息**
EFI文件直接使用的是本仓库当前的EFI文件，之前是10.15.2开机也报错，只能重新烧了个安装盘（已经下载不到10.15.3系统了）

**Comment by icyleaf** [comment]
升级前请先确认是否遵循了 #41 的确认事项，另外硬件信息来看 EFI 应该是适用的。从上面截图看不太出来是啥问题。你可以用 "PrelinkedKernels\PrelinkedKernel.deveopment" 作为关键词来搜索下，我是一直没有升级 10.15.4 可能对你帮助不太大

**Comment by huyinjie** [comment]
目前尝试了BIOS更新P4.2->P4.3 目前能正常进入系统 看起来像是某个内存兼容问题

**Comment by icyleaf** [comment]
我好像还在 1.2 版本 :grin:

是不是升级 BIOS 版本就已经解决问题了，如果是的话请关闭本问题，谢谢
