### ISSUE TITLE
我打算构建一台黑苹果，但是cpu和显卡和你不同，是否可以完全套用你的EFI？

### ISSUE THREAD

**Issue by telepathybuts** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#46]
主板和你相同，但是CPU是9900k，显卡是5700xt 50th，是否可以完全套用你的EFI文件？

**Comment by icyleaf** [comment]
主板一样基本上没大问题，[7500xt](https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/issues?q=label%3Arx5700-xt+is%3Aclosed)有支持。

**Comment by icyleaf** [comment]
成功了吗？有问题再开哈
