### ISSUE TITLE
升级 macOS 10.15.5

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#47]
待做事项：

- [x] 备份系统（TimeMachine 或 CCC） **重要，重要，重要**
- [x] 升级 Clover r5119

升级后状态：

第一次重启选择 Preboot 进入升级结束时依然提醒 `The bless tool was unable to set the current boot disk` 重启后选择正常启动引导进入系统发现已经显示升级至 10.15.5 并弹出正常的系统升级引导， 在 #41 的<del>显示器自动激活 HDR 问题已经没有了。</del> 睡眠后唤醒又有了，修复方法：系统设置-显示器，勾掉“高动态范围”的选项就好了，[原因](https://www.youtube.com/watch?v=CFyNBYP5lJk)是 macOS 10.15.4 开始会自动识别显示器设置并默认开启 HDR

个人猜测：

错误  `The bless tool was unable to set the current boot disk` 的可能原因是我之前使用的 SATA SSD 安装的 Windows 10 在更换 M.2 SSD 后数据是直接硬拷贝且 Windows 10 默认对于 M.2 SSD 的引导有需要单独设置，而我有病乱投医用了一堆的工具清了 MBR、重建和修复等操作成功把引导救了回来其实 Clover 引导的名字和之前也有所不太一样。因此造成引导有问题[有点类似这样的问题](http://bbs.pcbeta.com/viewthread-1842043-1-1.html)，虽然会报错但主要是 macOS 升级器重启找不到正常的引导而报错其实系统已经升级完毕，重启后手动选对启动引导就可以了。后续看看啥时候把 Windows 10 系统重做再说吧。暂时不管了。

Ref: https://www.tonymacx86.com/threads/macos-10-15-5-supplemental-update.298946/

**Comment by icyleaf** [comment]
修复 LG 或其他显示器默认开启 HDR 的问题：系统设置-显示器，勾掉“高动态范围”的选项

<img width="674" alt="截屏2020-06-26 17 35 03" src="https://user-images.githubusercontent.com/17814/85843575-ed926c00-b7d3-11ea-9675-48afd62e5477.png">

**Comment by icyleaf** [comment]
有个小问题，重启或开机时会一直保留升级的启动引导，需要想办法消掉

**Comment by chenjia14** [comment]
> 有个小问题，重启或开机时会一直保留升级的启动引导，需要想办法消掉

因为硬件差不多(除了CPU和显卡)，从开始配置黑苹果一直关注你的EFI，有几个小问题：
1.SMCHelper.efi 这个是跟FakeSMC联动的，既然已经替换为VirtualSMC.efi，应该删除
2.我看你这次替换为VirtualSMC没有把VirtualSMC相关联的tools文件夹复制过来，这个tools是没有作用的吗？我一直都是复制的，不过没搞清楚这个文件夹的作用
3.根据https://blog.xjn819.com/?p=317的内容，OsxAptioFix3Drv.efi有损坏设备的风险，建议升级为AptioMemoryFix.efi，我升级了没什么问题。
4.我测试的结果BCM94360CS2这张卡是完全免驱的，不需要蓝牙驱动就可以使用蓝牙，BrcmFirmwareRepo.kext和BrcmPatchRAM2.kext应该是可以删除的。
5. btw 升级的启动引导可以通过删除 /System/Volumes/Data/macOS Install Data 文件夹去除

**Comment by icyleaf** [comment]
> 1.SMCHelper.efi 这个是跟FakeSMC联动的，既然已经替换为VirtualSMC.efi，应该删除

感谢反馈，我晚上就删= =！

> 2.我看你这次替换为VirtualSMC没有把VirtualSMC相关联的tools文件夹复制过来，这个tools是没有作用的吗？我一直都是复制的，不过没搞清楚这个文件夹的作用

根据 [VirtualSMC FAQ](https://github.com/acidanthera/VirtualSMC/blob/9d84c867c3b2176129173bbb2cb3102de71b408d/Docs/FAQ_zh.md#%E8%BF%99%E4%BA%9B%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7%E9%83%BD%E6%9C%89%E4%BB%80%E4%B9%88%E4%BD%9C%E7%94%A8) 来看 tools 目录的文件都是命令行的附带工具和兼容 iStats Menus 的动态库。

> 3.根据 https://blog.xjn819.com/?p=317 的内容，OsxAptioFix3Drv.efi有损坏设备的风险，建议升级为AptioMemoryFix.efi，我升级了没什么问题。

呃，我记得之前我用的是 AptioMemoryFix.efi 怎么变成 OsxAptioFix3Drv.efi 了呢- -

> 4.我测试的结果BCM94360CS2这张卡是完全免驱的，不需要蓝牙驱动就可以使用蓝牙，BrcmFirmwareRepo.kext和BrcmPatchRAM2.kext应该是可以删除的。

当初是测试觉得自己的蓝牙耳机连接上不太稳定临时加上去的，后来也没发现有啥异常就留着了，虽然效果也没好哪去，我在测试测试蓝牙稳定性

> 5. btw 升级的启动引导可以通过删除 /System/Volumes/Data/macOS Install Data 文件夹去除

感谢！

**Comment by chenjia14** [comment]
这个BCM94360CS2的蓝牙效果奇差，连airpods pro会有卡顿，非苹果的蓝牙耳机是断断续续的。连trackpad2倒是没什么问题，隔空投送也可以正常使用，有些非苹果的蓝牙设备比如蓝牙键盘之类的甚至有时候都搜不到。我搞不清楚是不是我的拆机卡个例。我是直接把电脑放桌上，买了两个天线，信号按道理是没问题的，wifi也是正常使用。

**Comment by icyleaf** [comment]
同意，我是用的 QC35 会不定时偶发的时断时续的情况非常难受

**Comment by icyleaf** [comment]
目前没发现太大问题，暂时关闭

**Comment by EricESM** [comment]
请问我安装10.15.X时候黑屏 是什么原因？

**Comment by icyleaf** [comment]
你这么说我也不知道呢

**Comment by EricESM** [comment]
> 你这么说我也不知道呢

我今天发现我的电脑配置和这个人差不多一模一样，CPU，显卡，主板都一样。 

我安装教程用你的，后面的用他的efi， 我没有用无线网卡。

我改了一些efi 现在可以到白苹果安装进度哪里 但是要么进度条不动 要么进度条满了 不动

[https://github.com/haiyang1992/Hackintosh-Opencore-Asrock_Z390_Phantom_Gaming_ITX#hackintosh-opencore-asrock_z390_phantom_gaming_itx](url)

efi和你有些不一样

请问有任何建议吗 我觉得不太好意思用另外的efi来问你

**Comment by icyleaf** [comment]
他的 OpenCore 和我的 Clover 是两个不同的引导系统，建议你去他那边问，我这边爱莫能助。

**Comment by EricESM** [comment]
> 他的 OpenCore 和我的 Clover 是两个不同的引导系统，建议你去他那边问，我这边爱莫能助。

谢谢， 参考了你的和他的， 前两天安装完了

有个小问题，我读取不了GPU的温度，用了你说的HWMoniotrSMC2也不行， 请问是什么原因？
GPU： 5700 xt
![Screen Shot 2020-09-23 at 1 14 09 AM](https://user-images.githubusercontent.com/10945713/93985820-6c973200-fd3a-11ea-8722-0ca3fd729451.png)
