### ISSUE TITLE
升级10.15.6后，蓝牙不可用

### ISSUE THREAD

**Issue by ansonliao** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#49]
@icyleaf 好!
主板和妳的主板是一样的，无线模块也是和妳一样的 `BCM94360CS2`，升级完10.15.6后，蓝牙变成不可用状态，显示波浪横条，如下图
![image](https://user-images.githubusercontent.com/6060224/88176209-809ab680-cc59-11ea-9df0-435e1bfa256d.png)

根据妳的安装教程
![image](https://user-images.githubusercontent.com/6060224/88176273-97d9a400-cc59-11ea-8b3b-4efb2103485d.png)

1. 
将 `BrcmFirmwareRepo.kext` 和 `BrcmPatchRAM2.kext` 安装到 `/L/E`下面，不能解决蓝牙问题。

2.
 根据蓝牙补丁 `https://github.com/acidanthera/BrcmPatchRAM/blob/master/README.md` 里面说的，
将 `BrcmBluetoothInjector.kext`，`brcmPatchRAM3.kext`，`BrcmFirmwareData.kext` 安装到 `/L/E` 下面，仍然无法解决蓝牙问题。

3. 
根据蓝牙补丁 `https://github.com/acidanthera/BrcmPatchRAM/blob/master/README.md` 里面说的，
将 `BrcmBluetoothInjector.kext`，`brcmPatchRAM3.kext`，`BrcmFirmwareData.kext`，`BrcmNonPatchRAM2.kext`，`BrcmFirmwareRepo.kext` 不同的组合放在 `/L/E`下面，均不能解决蓝牙问题

请教 @icyleaf ，能否帮忙看看如何解决蓝牙不可用的问题?
谢谢!

**Comment by chenjia14** [comment]
我也升级1.15.6了，蓝牙没有出现问题，这个蓝牙是免驱的，应该不是驱动的问题，如果你的配置跟@icyleaf一样，应该也不太可能是USB的问题，你可以试试重置nvram或者给主板放电BIOS恢复出厂设置。如果还是不行，可以在WINDOWS下面测一下蓝牙还能不能驱动。

**Comment by ansonliao** [comment]
@chenjia14 
1. 
重置nvram好几回了，没效果

2. 
说来惭愧，家里没有windows的电脑，现在这个黑果也是没装windows，所以没办法在windows下面试蓝牙

3.
现在就差重置bios了

**Comment by icyleaf** [comment]
建议先回滚系统，因为 macOS 后续的限制已经不允许把 kexts 放在系统 `/Libaray` 下，同时 [47#issuecomment-650982536](https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/issues/47#issuecomment-650982536) 里 @chenjia14 已经明白说了 `BCM94360CS2` 是免驱的。确认配置是否跟我的一样，如果不一样备份好你现在的把我的替换过去试试看

**Comment by ansonliao** [comment]
@icyleaf 
了解!
主板和无线卡型号是一样的， 我的 cpu是9600K，显卡是蓝宝石的rx5500 xt 8G，模拟的型号是iMac19,1
如果用妳的EFI，我需要额外配置些什么吗?

**Comment by icyleaf** [comment]
EFI 应该是支持核显的，你可以把线换下直接用。

**Comment by icyleaf** [comment]
长时间没有回复，暂时关闭有问题再开。

**Comment by ansonliao** [comment]
不好意思，最近忙于其它事情，还没解决。打算恢复试试。

**Comment by icyleaf** [comment]
没事有问题随时重新开启

**Comment by ansonliao** [comment]
重装10.15.6和降级重装10.15.5，都无法解决蓝牙问题，估计无线网卡模块要么接触不好，要么就是蓝牙模块坏了。
下一步试试重新安装无线网卡

**Comment by ansonliao** [comment]
@icyleaf @chenjia14 
更新最新状态，是转接卡坏了，应该是短路了，换了新的转接卡就蓝牙就恢复了。
另外，最好在无线网卡背面和转接卡与主板固定的螺丝处都贴上绝缘胶布。
