### ISSUE TITLE
9600K重装后，发现只有独显，不显示核显信息了

### ISSUE THREAD

**Issue by TrainTsang** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#50]
**问题描述**

1、我以前使用的是9400，当年装的10.15.1，后续升级到10.15.4，能同时核显+独显使用
2、最近升级到了9600K，就直接重装了10.15.4，主板也打开了iGPU，结果发现无法识别到iGPU了，只能识别到独显，板载接口页无输出
3、使用黑果小兵原版的时候，是能正常识别两张显卡的

**Comment by icyleaf** [comment]
那请用黑果小兵原版，个人没有此类特别需求

**Comment by icyleaf** [comment]
长时间没有回复，暂时关闭有问题再开。
