### ISSUE TITLE
升级 macOS Big Sur 11.0 + 迁移 OpenCore

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#51]
### 待做事项

- [x] 备份系统（TimeMachine 或 CCC） 重要，重要，重要
- [x] 烧录系统 U 盘备用
- [x] 升级必要 kexts
- [x] 下载 macOS Big Sur dmg 
- [x] 备用系统 U 盘使用 OpenCore 0.6.7 做启动 EFI
- [x] 替换系统 EFI 的 Clover 至 OpenCore 0.6.7
- [x] 保证现在版本使用 OpenCore 正常启动
- [x] 其他
  - [x] 硬件是否正常
  - [x] 账户服务是否正常
  - [x] 其他问题

### 为什么迁移至 OpenCore?

根据下面 tonymacx86 第一个链接里面内容不止一个人提到升级 Clover 到必要的版本后重启会提示找不到系统均使用 OpenCore 解决，这个是最大的原因。

### 相关参考

- https://www.tonymacx86.com/threads/update-directly-to-macos-big-sur.304629/
- https://www.codejam.info/2020/11/upgrading-hackintosh-catalina-big-sur-clover-opencore.html
- https://dortania.github.io/hackintosh/updates/2020/11/12/bigsur-new.html

**Comment by icyleaf** [comment]
没有升级的欲望- -！

**Comment by buaazp** [comment]
hello 咨询下迁移过程中有没有遇到什么 block 的地方？
我之前一直用你这套配置在 clover 引导都挺好，最近因为必须得开 filevault 加密想尝试下切到 opencore。
我看网上说的迁移方法貌似比较简单，你这边如果已经遇到啥坑的话可以大概说一下避免走弯路。感谢。

**Comment by icyleaf** [comment]
WIP 的意思是 Working in process 还在进行中，所以我还没来得及折腾，上面只是对于我进行的 todo 和参考内容。希望节后能够升级完成 🤣

**Comment by icyleaf** [comment]
已迁移至 OpenCore 11cfad6a84c4fa72e68114c7938c59a1ef468a27

**Comment by icyleaf** [comment]
直接使用系统升级无痛到 Big Sur

**Comment by icyleaf** [comment]
系统无痛已经更新至 11.2.3，启用了 Modern 主题 9f87bae01ce89e73a0a0826ccbc0ada6e9e255ca e07c9cb7c2a8477c80ff6118ce44c183d0605c87 

<img width="888" alt="截屏2021-03-27 23 17 48" src="https://user-images.githubusercontent.com/17814/112725466-64bb8300-8f53-11eb-8ca0-d8b410c87eb0.png">

目前除了 AirDrop 其他一切正常。

**Comment by icyleaf** [comment]
10.15 和 11.2.3 的 Geekbench 4 对比测试结果 https://browser.geekbench.com/v4/cpu/compare/14931592?baseline=16102413

**Comment by icyleaf** [comment]
> 系统无痛已经更新至 11.2.3，启用了 Modern 主题 [9f87bae](https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/commit/9f87bae01ce89e73a0a0826ccbc0ada6e9e255ca) [e07c9cb](https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/commit/e07c9cb7c2a8477c80ff6118ce44c183d0605c87)
> 
> <img alt="截屏2021-03-27 23 17 48" width="888" src="https://user-images.githubusercontent.com/17814/112725466-64bb8300-8f53-11eb-8ca0-d8b410c87eb0.png">
> 
> 目前除了 AirDrop 其他一切正常。

问题在于需要 reset nvram，之前一直用的是终端，正确的方法是需要从引导菜单选择 reset nvram 之后才正常，包括之前总是显示老版本的 opencore 版本号也是这个问题。
