### ISSUE TITLE
一直在使用本仓库的EFI, 能提供一下从clover升级到OC的流程说明

### ISSUE THREAD

**Issue by qbeenslee** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#53]
其实是想楼主出一个懒人版本的迁移教程.

由于对OC了解有限, 这里提出我关心的问题:
***"之前是使用本仓库的clover/EFI, 迁移成OC是不是直接使用当前本EFI仓库内容, 替换其中的机器码等即可"***

**Comment by icyleaf** [comment]
如果硬件尤其是主板，独立显卡一致的情况下可以无脑使用的，升级 OpenCore 需要在引导那里面 reset 下 nvram，具体参见 #51
