### ISSUE TITLE
原Clover升级本OC问题反馈

### ISSUE THREAD

**Issue by qbeenslee** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#54]
**问题描述**

OC启动过程失败

**硬件信息**

- 主板：same
- CPU：same
- 显卡：same

**软件信息**
- 系统版本: macOS Catalina 10.15.7
- opencore 版本：0.6.7

---

使用EFI  https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/commit/3f8a1c2291c13bb18f55cc40606edc0205db91ac

## 1. opencore报kexts缺失

opencore启动过程中报'xxx.kext is missing for start inject... ', 缺失kext如下:
- AirportBrcmFixup.kext
- BrcmBluetoothInjector.kext
- BrcmFirmwareData.kext
- BrcmPatchRAM3.kext
- SMCDellSensors.kext

> 解决方式: 下载添加缺失kext

## 2. opencore启动过程一直停留在 `mac framework successfully initialized`附近

> 解决方式: 参考http://bbs.pcbeta.com/viewthread-1841451-1-1.html , 设置`ReleaseUSBOwnership `为`True`

**Comment by qbeenslee** [comment]
## 3. 不支持无GPU启动
拆除显卡无法启动, 卡在opencore启动过程

**Comment by icyleaf** [comment]
迁移分解参见 #51 ，Opencore 配置部分我刚稍微更新到里面了，主要参考官方的两个文档。

**Comment by linseedoil** [comment]
> ## 3. 不支持无GPU启动
> 拆除显卡无法启动, 卡在opencore启动过程

同样的问题。前几天我看显卡涨的凶就把显卡卖了，最近准备迁移到oc上，结果无法启动，会卡在白苹果logo。已经参照官方指导改了AAPL,ig-platform-id也不行

07009B3E | Used when the Desktop iGPU is used to drive a display
-- | --
00009B3E | Alternative to 07009B3E if it doesn't work

**Comment by icyleaf** [comment]
OpenCore 独显和核显的配置方式是没法共用的，除了修改 `AAPL,ig-platform-id` 还需要改配套的 `framebuffer-patch-enable` 和 `framebuffer-stolenmem` 这俩是开启显卡缓冲区补丁开启和修正显卡内存大小的

**Comment by linseedoil** [comment]
> OpenCore 独显和核显的配置方式是没法共用的，除了修改 `AAPL,ig-platform-id` 还需要改配套的 `framebuffer-patch-enable` 和 `framebuffer-stolenmem` 这俩是开启显卡缓冲区补丁开启和修正显卡内存大小的

是的，我是参照的官方配置都改过了的还是不行


> Key | Type | Value
> -- | -- | --
> AAPL,ig-platform-id | Data | 07009B3E
> framebuffer-patch-enable | Data | 01000000
> framebuffer-stolenmem | Data | 00003001
> (This is an example for a desktop UHD 630 without a dGPU and no BIOS options for iGPU memory)

**Comment by icyleaf** [comment]
假期刚回来，我目前没有时间测试这个问题，要不你参考下 https://github.com/seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-BigSur 这个 EFI 他里面有区分独显和核显的配置

**Comment by icyleaf** [comment]
暂无回复，关闭处理
