### ISSUE TITLE
升级 macOS Big Sur 12.3.1

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#55]
- [x] 备份系统（TimeMachine 或 CCC） 重要，重要，重要
- [x] 备用系统 U 盘复制系统 EFI 备份
- [x] 升级 OpenCore 0.6.9
- [x] 升级必要 kexts
- [x] 升级 ACPI

**Comment by icyleaf** [comment]
<img width="586" alt="截屏2021-05-09 15 40 28" src="https://user-images.githubusercontent.com/17814/117564113-f682e800-b0dc-11eb-8c52-b5d38445e7a4.png">

提交 d35ebac65eb1ccb7473d9fe00472c7caa22428d3  bb9de4e4de48f5c7972cef55d3a4c632e909ece9

**Comment by raymond2010** [comment]
i9900，RX5700XT，需要额外做什么设置上的修改吗？

**Comment by icyleaf** [comment]
看这里：https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#navi-10-series
