### ISSUE TITLE
什么时候更新Monterey呢？

### ISSUE THREAD

**Issue by terryops** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#58]
我自行更新后，没办法进入系统了。

**Comment by icyleaf** [comment]
暂无计划，网上有爆出部分机型升级会有一些缺陷再观察一段时间，对于你的问题请参考 [upgrade](https://github.com/icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX/issues?q=label%3Aupgrade+is%3Aclosed) 的 TODO，如果无视无脑升级的两种方法解决：

1. 制作一个 macOS 的启动 U 盘并把适用于 10.15 的 EFI 替换到 EFi 分区之后使用它引导就可以进入，进入原来系统把 U 盘的 EFI 替换到系统的就可以了
2. 同样先准备一份使用于 10.15 的 EFI，然后找一个可以进入恢复模式的系统（macOS 或 Windows 都行），然后把系统的 EFI 分区打开并替换重启就好了
