### ISSUE TITLE
安装时卡住

### ISSUE THREAD

**Issue by ttdevs** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#6]
安装时，从Clover选择U盘，然后引导到苹果安装界面，这个时候选择磁盘工具会卡住，或者直接选择某盘也会卡住，卡住后鼠标就也不能用了，放任卡半小时就也不会好。针对这样的情况，怎么查找原因呢？搜什么样的关键字？
这个时候能导出或者查看系统log吗？如果可以怎么操作?
谢谢

**Comment by icyleaf** [comment]
尝试该用有线或者 2.4G 鼠标，EFI 启动日志可以通过启动参数追加，我的 EFI 是开启的，你说的这种情况可以看看 macOS 的日志，貌似进入安装界面，不选择进入磁盘工具可以在菜单工具选择查看日志？我不太记得了，实在没有可以开终端，一般系统日志在 /var/log 目录下面。

**Comment by ttdevs** [comment]
感谢，折腾了两周，终于成功了~~
