### ISSUE TITLE
之前把独立显卡卖掉了，配置同楼主的一样，也遇到引导卡住的问题了，按照之前ISSUE里的回答没有解决掉，可以给一些建议吗

### ISSUE THREAD

**Issue by directz** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#60]

**Comment by icyleaf** [comment]
核显参考官方教程：https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#deviceproperties

**Comment by directz** [comment]
非常感谢，按照教程，已经搞定了

**Comment by huyinjie** [comment]
@directz 我也遇到的同样的问题，请问你现在的系统版本是？

**Comment by icyleaf** [comment]
跟系统是没有关系的
