### ISSUE TITLE
amd 6900xt 公版 有人黑过吗  

### ISSUE THREAD

**Issue by lylala8** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#69]
**问题描述**
6900xt 能装黑苹果吗  要做那些配置
描述你出现的问题

**硬件信息**

- 主板：asrock z90 itx
- CPU：i7 8700
- 显卡：amd 6900xt

**软件信息**

- Clover 版本：
- 相关 Kexts 和版本：

** Clover 配置**

有必要可以上传 Clover 的配置文件

**截图**

如果需要可以附加上

**Comment by icyleaf** [comment]
https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#navi-21-series
