### ISSUE TITLE
主题失效

### ISSUE THREAD

**Issue by lylala8** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#72]
发现没有主题但是config里配置了blackosx\BsxM1 主题 资源文件也都齐全 进oc左上角原生几个选择项，自己配置主题也无效 不清楚什么原因

**Comment by lylala8** [comment]
解决了，可能是oc 缺少文件导致的 重新同步一下就好了

**Comment by icyleaf** [comment]
参考官方教程 https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html
