### ISSUE TITLE
雷电接口失效

### ISSUE THREAD

**Issue by lylala8** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#73]
bios刷固件后 11系统能直接使用 更新到12系统 找不到雷电设备了，有没有大佬了解这块的

**Comment by icyleaf** [comment]
我不太用雷电口，从始至终没有折腾过这块

**Comment by lylala8** [comment]
可能是usb定制的问题  我晚点去掉个usb3 加个雷电口看看

**Comment by lylala8** [comment]
通过ssdt 文件加上了雷电  只不过在设置里不显示设备

**Comment by lylala8** [comment]
通过ssdt 文件加上了雷电  只不过在设置里不显示设备
