### ISSUE TITLE
升级 macOS Sonoma 14.1

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#77]
- [x] 备份系统（TimeMachine 或 CCC） 重要，重要，重要
- [x] 备用系统 U 盘复制系统 EFI 备份
- [x] 升级 OpenCore 0.9.3+
- [x] 升级必要 kexts: [Lilu.kext](https://github.com/vit9696/Lilu/releases), [AppleALC.kext](https://github.com/acidanthera/AppleALC/releases) and [WhateverGreen.kext](https://github.com/acidanthera/WhateverGreen/releases).
- [ ] 网卡不再支持，需要使用 [OpenCore-Legacy-Patcher](https://github.com/dortania/OpenCore-Legacy-Patcher/)

**Comment by tuutoo** [comment]
无线网卡用不了，是因为这个吗？
这个怎么用啊？能出个教程吗？谢谢~
网卡不再支持，需要使用 [OpenCore-Legacy-Patcher](https://github.com/dortania/OpenCore-Legacy-Patcher/)

**Comment by icyleaf** [comment]
不打算升级了，新特性没一个有吸引力的，官网链接都已经给了按照教程安装配置即可。
