### ISSUE TITLE
无线网卡

### ISSUE THREAD

**Issue by YiStick** [icyleaf/EFI-ASRock-Z390-Phantom-Gaming-ITX#8]
我找到你买的那家了。我的主板是微星的z390itx不知道可不可以成功，而且也是拆的wifi模块那里，我看你的图是一样的。

**Comment by icyleaf** [comment]
不一定。特别提醒：主板自带 M.2 Key E 插口的无线模块需要支持非 CNVi 网卡才能使用，具体看我博客攒了一台黑苹果那篇文章
